spring:
  application:
    name: erp-system
  datasource:
    url: jdbc:mysql://localhost:3306/erp_schema
    password: dumith
    username: dumith
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#       dialect: org.hibernate.dialect.MySQL8Dialect